<a href="https://colab.research.google.com/github/krishnan5307/-5307-krishnan/blob/main/Flight_Delay_Recommendation_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Flight Delay Recommendation/T_ONTIME_REPORTING.csv")#, names=column_names)

In [ ]:
df.head(5)

YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK               FL_DATE  \
0  2023        1      1             1            7  1/1/2023 12:00:00 AM   
1  2023        1      1             1            7  1/1/2023 12:00:00 AM   
2  2023        1      1             1            7  1/1/2023 12:00:00 AM   
3  2023        1      1             1            7  1/1/2023 12:00:00 AM   
4  2023        1      1             1            7  1/1/2023 12:00:00 AM   

  OP_UNIQUE_CARRIER  OP_CARRIER_AIRLINE_ID OP_CARRIER  OP_CARRIER_FL_NUM  ...  \
0                9E                  20363         9E               4647  ...   
1                9E                  20363         9E               4650  ...   
2                9E                  20363         9E               4650  ...   
3                9E                  20363         9E               4654  ...   
4                9E                  20363         9E               4663  ...   

   CANCELLATION_CODE  DIVERTED  CRS_ELAPSED_TIME ACTUAL_ELAPSED_TIME AIR_TIME  \
0                NaN       0.0             122.0                97.0     72.0   
1                NaN       0.0             117.0               107.0     82.0   
2                NaN       0.0             146.0               119.0     91.0   
3                NaN       0.0             141.0               123.0     89.0   
4                NaN       0.0             208.0               203.0    174.0   

   FLIGHTS  CARRIER_DELAY  WEATHER_DELAY SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0      1.0            NaN            NaN            NaN                  NaN  
1      1.0            NaN            NaN            NaN                  NaN  
2      1.0            NaN            NaN            NaN                  NaN  
3      1.0            NaN            NaN            NaN                  NaN  
4      1.0            NaN            NaN            NaN                  NaN  

[5 rows x 36 columns]

In [ ]:
df.shape

(59610, 36)

In [ ]:
df.dtypes

YEAR                       int64
QUARTER                    int64
MONTH                      int64
DAY_OF_MONTH               int64
DAY_OF_WEEK                int64
FL_DATE                   object
OP_UNIQUE_CARRIER         object
OP_CARRIER_AIRLINE_ID      int64
OP_CARRIER                object
OP_CARRIER_FL_NUM          int64
ORIGIN_AIRPORT_ID          int64
ORIGIN_AIRPORT_SEQ_ID      int64
ORIGIN_CITY_MARKET_ID      int64
ORIGIN_CITY_NAME          object
ORIGIN_STATE_ABR          object
DEST_AIRPORT_ID            int64
DEST_AIRPORT_SEQ_ID        int64
DEST_CITY_MARKET_ID        int64
DEST_CITY_NAME            object
DEP_TIME                 float64
DEP_DELAY                float64
DEP_DELAY_NEW            float64
ARR_TIME                 float64
ARR_DELAY                float64
ARR_DELAY_NEW            float64
CANCELLED                float64
CANCELLATION_CODE         object
DIVERTED                 float64
CRS_ELAPSED_TIME         float64
ACTUAL_ELAPSED_TIME      float64
AIR_TIME  

In [ ]:
column_dtypes = df.dtypes.value_counts()

print(column_dtypes)

float64    16
int64      13
object      7
dtype: int64


In [ ]:
df.isnull().sum()

YEAR                         0
QUARTER                      0
MONTH                        0
DAY_OF_MONTH                 0
DAY_OF_WEEK                  0
FL_DATE                      0
OP_UNIQUE_CARRIER            0
OP_CARRIER_AIRLINE_ID        0
OP_CARRIER                   0
OP_CARRIER_FL_NUM            0
ORIGIN_AIRPORT_ID            0
ORIGIN_AIRPORT_SEQ_ID        0
ORIGIN_CITY_MARKET_ID        0
ORIGIN_CITY_NAME             0
ORIGIN_STATE_ABR             0
DEST_AIRPORT_ID              0
DEST_AIRPORT_SEQ_ID          0
DEST_CITY_MARKET_ID          0
DEST_CITY_NAME               0
DEP_TIME                   823
DEP_DELAY                  824
DEP_DELAY_NEW              824
ARR_TIME                   880
ARR_DELAY                 1004
ARR_DELAY_NEW             1004
CANCELLED                    0
CANCELLATION_CODE        58738
DIVERTED                     0
CRS_ELAPSED_TIME             0
ACTUAL_ELAPSED_TIME       1004
AIR_TIME                  1004
FLIGHTS                      0
CARRIER_

In [ ]:
# Assuming you have a DataFrame called 'df' and a categorical column called 'Category'
value_counts = df['CANCELLED'].value_counts()

print(value_counts)

0.0    58738
1.0      872
Name: CANCELLED, dtype: int64


In [ ]:
df["QUARTER"].unique()

array([1])

In [ ]:
data =df.copy()

In [ ]:
data.drop(["YEAR","QUARTER","MONTH", "FL_DATE","OP_CARRIER_AIRLINE_ID", "ORIGIN_AIRPORT_SEQ_ID","DEST_AIRPORT_SEQ_ID","CANCELLATION_CODE"], axis=1,inplace= True)

In [ ]:
data.drop(["ARR_DELAY_NEW","DEP_DELAY_NEW",], axis=1,inplace= True)

In [ ]:
data.head()

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER OP_CARRIER  OP_CARRIER_FL_NUM  \
0             1            7                9E         9E               4647   
1             1            7                9E         9E               4650   
2             1            7                9E         9E               4650   
3             1            7                9E         9E               4654   
4             1            7                9E         9E               4663   

   ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID ORIGIN_CITY_NAME ORIGIN_STATE_ABR  \
0              12953                  31703     New York, NY               NY   
1              11996                  31871        Greer, SC               SC   
2              12953                  31703     New York, NY               NY   
3              12478                  31703     New York, NY               NY   
4              12478                  31703     New York, NY               NY   

   DEST_AIRPORT_ID  ...  CANCELLED DIVERTED  CRS_ELAPSED_TIME  \
0            14492  ...        0.0      0.0             122.0   
1            12953  ...        0.0      0.0             117.0   
2            11996  ...        0.0      0.0             146.0   
3            11433  ...        0.0      0.0             141.0   
4            13487  ...        0.0      0.0             208.0   

   ACTUAL_ELAPSED_TIME  AIR_TIME  FLIGHTS  CARRIER_DELAY  WEATHER_DELAY  \
0                 97.0      72.0      1.0            NaN            NaN   
1                107.0      82.0      1.0            NaN            NaN   
2                119.0      91.0      1.0            NaN            NaN   
3                123.0      89.0      1.0            NaN            NaN   
4                203.0     174.0      1.0            NaN            NaN   

   SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0             NaN                  NaN  
1             NaN                  NaN  
2             NaN                  NaN  
3             NaN                  NaN  
4             NaN                  NaN  

[5 rows x 26 columns]

In [ ]:
data.dtypes

DAY_OF_MONTH               int64
DAY_OF_WEEK                int64
OP_UNIQUE_CARRIER         object
OP_CARRIER                object
OP_CARRIER_FL_NUM          int64
ORIGIN_AIRPORT_ID          int64
ORIGIN_CITY_MARKET_ID      int64
ORIGIN_CITY_NAME          object
ORIGIN_STATE_ABR          object
DEST_AIRPORT_ID            int64
DEST_CITY_MARKET_ID        int64
DEST_CITY_NAME            object
DEP_TIME                 float64
DEP_DELAY                float64
ARR_TIME                 float64
ARR_DELAY                float64
CANCELLED                float64
DIVERTED                 float64
CRS_ELAPSED_TIME         float64
ACTUAL_ELAPSED_TIME      float64
AIR_TIME                 float64
FLIGHTS                  float64
CARRIER_DELAY            float64
WEATHER_DELAY            float64
SECURITY_DELAY           float64
LATE_AIRCRAFT_DELAY      float64
dtype: object

In [ ]:
column_dtypes = data.dtypes.value_counts()

print(column_dtypes)

float64    14
int64       7
object      5
dtype: int64


In [ ]:
for u, x, y in zip(data.columns,data.dtypes,data.isnull().sum()):
  print(y,x,u)

0 int64 DAY_OF_MONTH
0 int64 DAY_OF_WEEK
0 object OP_UNIQUE_CARRIER
0 object OP_CARRIER
0 int64 OP_CARRIER_FL_NUM
0 int64 ORIGIN_AIRPORT_ID
0 int64 ORIGIN_CITY_MARKET_ID
0 object ORIGIN_CITY_NAME
0 object ORIGIN_STATE_ABR
0 int64 DEST_AIRPORT_ID
0 int64 DEST_CITY_MARKET_ID
0 object DEST_CITY_NAME
823 float64 DEP_TIME
824 float64 DEP_DELAY
880 float64 ARR_TIME
1004 float64 ARR_DELAY
0 float64 CANCELLED
0 float64 DIVERTED
0 float64 CRS_ELAPSED_TIME
1004 float64 ACTUAL_ELAPSED_TIME
1004 float64 AIR_TIME
0 float64 FLIGHTS
45995 float64 CARRIER_DELAY
45995 float64 WEATHER_DELAY
45995 float64 SECURITY_DELAY
45995 float64 LATE_AIRCRAFT_DELAY


In [ ]:
data.head(5)

DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER OP_CARRIER  OP_CARRIER_FL_NUM  \
0             1            7                9E         9E               4647   
1             1            7                9E         9E               4650   
2             1            7                9E         9E               4650   
3             1            7                9E         9E               4654   
4             1            7                9E         9E               4663   

   ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID ORIGIN_CITY_NAME ORIGIN_STATE_ABR  \
0              12953                  31703     New York, NY               NY   
1              11996                  31871        Greer, SC               SC   
2              12953                  31703     New York, NY               NY   
3              12478                  31703     New York, NY               NY   
4              12478                  31703     New York, NY               NY   

   DEST_AIRPORT_ID  ...  CANCELLED DIVERTED  CRS_ELAPSED_TIME  \
0            14492  ...        0.0      0.0             122.0   
1            12953  ...        0.0      0.0             117.0   
2            11996  ...        0.0      0.0             146.0   
3            11433  ...        0.0      0.0             141.0   
4            13487  ...        0.0      0.0             208.0   

   ACTUAL_ELAPSED_TIME  AIR_TIME  FLIGHTS  CARRIER_DELAY  WEATHER_DELAY  \
0                 97.0      72.0      1.0            NaN            NaN   
1                107.0      82.0      1.0            NaN            NaN   
2                119.0      91.0      1.0            NaN            NaN   
3                123.0      89.0      1.0            NaN            NaN   
4                203.0     174.0      1.0            NaN            NaN   

   SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0             NaN                  NaN  
1             NaN                  NaN  
2             NaN                  NaN  
3             NaN                  NaN  
4             NaN                  NaN  

[5 rows x 26 columns]

In [ ]:
data["CARRIER_DELAY"]  ## delay in minutes

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
59605    0.0
59606    NaN
59607    NaN
59608    NaN
59609    0.0
Name: CARRIER_DELAY, Length: 59610, dtype: float64

In [ ]:
# Assuming you have a DataFrame called 'data' and want to replace null values with 0 in specific columns
for feature in ["CARRIER_DELAY", "WEATHER_DELAY", "SECURITY_DELAY", "LATE_AIRCRAFT_DELAY"]:
    data[feature] = data[feature].fillna(0)


In [ ]:

# Assuming you have a DataFrame called 'data' and want to fill null values with the mean in specific columns
columns_to_fill = ["ACTUAL_ELAPSED_TIME", "AIR_TIME","DEP_TIME", "DEP_DELAY", "ARR_TIME","ARR_DELAY"]

for column in columns_to_fill:
    data[column].fillna(data[column].mean(), inplace=True)

In [ ]:
for u, x, y in zip(data.columns,data.dtypes,data.isnull().sum()):
  print(y,x,u)

0 int64 DAY_OF_MONTH
0 int64 DAY_OF_WEEK
0 object OP_UNIQUE_CARRIER
0 object OP_CARRIER
0 int64 OP_CARRIER_FL_NUM
0 int64 ORIGIN_AIRPORT_ID
0 int64 ORIGIN_CITY_MARKET_ID
0 object ORIGIN_CITY_NAME
0 object ORIGIN_STATE_ABR
0 int64 DEST_AIRPORT_ID
0 int64 DEST_CITY_MARKET_ID
0 object DEST_CITY_NAME
0 float64 DEP_TIME
0 float64 DEP_DELAY
0 float64 ARR_TIME
0 float64 ARR_DELAY
0 float64 CANCELLED
0 float64 DIVERTED
0 float64 CRS_ELAPSED_TIME
0 float64 ACTUAL_ELAPSED_TIME
0 float64 AIR_TIME
0 float64 FLIGHTS
0 float64 CARRIER_DELAY
0 float64 WEATHER_DELAY
0 float64 SECURITY_DELAY
0 float64 LATE_AIRCRAFT_DELAY


In [ ]:
for feature in data.columns:
    if data[feature].dtype == "object":
        unique_values = data[feature].unique()
        print(feature, unique_values, len(unique_values))



OP_UNIQUE_CARRIER ['9E' 'AA' 'AS' 'B6' 'DL' 'F9' 'G4' 'HA' 'MQ' 'NK' 'OH' 'OO' 'UA' 'WN'
 'YX'] 15
OP_CARRIER ['9E' 'AA' 'AS' 'B6' 'DL' 'F9' 'G4' 'HA' 'MQ' 'NK' 'OH' 'OO' 'UA' 'WN'
 'YX'] 15
ORIGIN_CITY_NAME ['New York, NY' 'Greer, SC' 'Asheville, NC' 'Albany, NY' 'Detroit, MI'
 'Raleigh/Durham, NC' 'Nashville, TN' 'Rochester, NY' 'Cincinnati, OH'
 'Memphis, TN' 'Norfolk, VA' 'Atlanta, GA' 'White Plains, NY'
 'Buffalo, NY' 'Providence, RI' 'Ithaca/Cortland, NY' 'Minneapolis, MN'
 'Cleveland, OH' 'Syracuse, NY' 'Indianapolis, IN' 'Wilmington, NC'
 'Portland, ME' 'Charleston, SC' 'Milwaukee, WI' 'Omaha, NE'
 'Savannah, GA' 'Burlington, VT' 'Chicago, IL' 'Charlotte, NC'
 'Baltimore, MD' 'St. Louis, MO' 'Bangor, ME' 'Los Angeles, CA'
 'Dallas/Fort Worth, TX' 'Austin, TX' 'Miami, FL' 'Washington, DC'
 'Phoenix, AZ' 'San Francisco, CA' 'Eagle, CO' 'Santa Ana, CA'
 'Charlotte Amalie, VI' 'Seattle, WA' 'San Diego, CA' 'Portland, OR'
 'Fort Lauderdale, FL' 'Boston, MA' 'San Juan, PR'
 'West Pal

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Assuming you have a DataFrame called 'data' with categorical columns
categorical_columns = ["OP_UNIQUE_CARRIER","OP_CARRIER","ORIGIN_CITY_NAME", "ORIGIN_STATE_ABR", "DEST_CITY_NAME"]

label_encoder = LabelEncoder()

for column in categorical_columns:
    data[column] = label_encoder.fit_transform(data[column])

In [ ]:
data.head()

DAY_OF_MONTH  DAY_OF_WEEK  OP_UNIQUE_CARRIER  OP_CARRIER  \
0             1            7                  0           0   
1             1            7                  0           0   
2             1            7                  0           0   
3             1            7                  0           0   
4             1            7                  0           0   

   OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID  \
0               4647              12953                  31703   
1               4650              11996                  31871   
2               4650              12953                  31703   
3               4654              12478                  31703   
4               4663              12478                  31703   

   ORIGIN_CITY_NAME  ORIGIN_STATE_ABR  DEST_AIRPORT_ID  ...  CANCELLED  \
0                62                25            14492  ...        0.0   
1                36                32            12953  ...        0.0   
2                62                25            11996  ...        0.0   
3                62                25            11433  ...        0.0   
4                62                25            13487  ...        0.0   

   DIVERTED  CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME  AIR_TIME  FLIGHTS  \
0       0.0             122.0                 97.0      72.0      1.0   
1       0.0             117.0                107.0      82.0      1.0   
2       0.0             146.0                119.0      91.0      1.0   
3       0.0             141.0                123.0      89.0      1.0   
4       0.0             208.0                203.0     174.0      1.0   

   CARRIER_DELAY  WEATHER_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0            0.0            0.0             0.0                  0.0  
1            0.0            0.0             0.0                  0.0  
2            0.0            0.0             0.0                  0.0  
3            0.0            0.0             0.0                  0.0  
4            0.0            0.0             0.0                  0.0  

[5 rows x 26 columns]

In [ ]:
column_dtypes = data.dtypes.value_counts()

print(column_dtypes)         ## No more label columns

float64    14
int64      12
dtype: int64


In [ ]:
data.shape

(59610, 26)

In [ ]:
for feature in ["OP_UNIQUE_CARRIER","OP_CARRIER","ORIGIN_CITY_NAME", "ORIGIN_STATE_ABR", "DEST_CITY_NAME"]:
  print(feature,data[feature].unique())

OP_UNIQUE_CARRIER [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
OP_CARRIER [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
ORIGIN_CITY_NAME [ 62  36   2   1  28  81  60  85  19  54  66   3 105  11  79  42  57  20
 100  40 106  77  14  56  68  95  13  18  16   5  97   6  51  24   4  55
 103  73  90  29  93  15  96  89  78  32   9  91 104  70 107  33  86  94
  44  88  39  61  71  26  45 101  48  69  12   0  87  76  82  10  38  41
  64  92  75  98  80  59  72  30  63  23 102  74  35  22  52  50  67  46
  17  31  83  53  37   7  65  25  84  58  43  47  34   8  21  27  99  49]
ORIGIN_STATE_ABR [25 32 21 17 33 12 36  7 31 18 26 11 16 40 22 38 10 15 19  3 34  6  2  4
 37 39 28 14 30 13 24 35 20  8 29 23 27  1  5 41  0  9]
DEST_CITY_NAME [ 81  62  36  28  57   2   1  11  60  56  16  85  54  77  66 105   3  42
  14  95  20 100 106  40  19  13  45  18   6  79  97   5  68  51  24  55
 103  73  29  90   4  15  93  96  89  78 104  70   9  48 101  44  33  32
  91  86  94  61  71  39  26   0  69  12 

In [ ]:
data.head()

DAY_OF_MONTH  DAY_OF_WEEK  OP_UNIQUE_CARRIER  OP_CARRIER  \
0             1            7                  0           0   
1             1            7                  0           0   
2             1            7                  0           0   
3             1            7                  0           0   
4             1            7                  0           0   

   OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID  \
0               4647              12953                  31703   
1               4650              11996                  31871   
2               4650              12953                  31703   
3               4654              12478                  31703   
4               4663              12478                  31703   

   ORIGIN_CITY_NAME  ORIGIN_STATE_ABR  DEST_AIRPORT_ID  ...  CANCELLED  \
0                62                25            14492  ...        0.0   
1                36                32            12953  ...        0.0   
2                62                25            11996  ...        0.0   
3                62                25            11433  ...        0.0   
4                62                25            13487  ...        0.0   

   DIVERTED  CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME  AIR_TIME  FLIGHTS  \
0       0.0             122.0                 97.0      72.0      1.0   
1       0.0             117.0                107.0      82.0      1.0   
2       0.0             146.0                119.0      91.0      1.0   
3       0.0             141.0                123.0      89.0      1.0   
4       0.0             208.0                203.0     174.0      1.0   

   CARRIER_DELAY  WEATHER_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY  
0            0.0            0.0             0.0                  0.0  
1            0.0            0.0             0.0                  0.0  
2            0.0            0.0             0.0                  0.0  
3            0.0            0.0             0.0                  0.0  
4            0.0            0.0             0.0                  0.0  

[5 rows x 26 columns]

In [ ]:
# ## Divide the dataset into independent and dependent features

# X=data.iloc[:,3:13]
# y=data.iloc[:,13]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input


# Split the input features (X) and target variables (y)
X = data.drop(['CANCELLED', 'ACTUAL_ELAPSED_TIME','CARRIER_DELAY', 'WEATHER_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY'], axis=1)
y_flight_duration = data['ACTUAL_ELAPSED_TIME']
y_cancelled = data['CANCELLED']
y_delay_reasons = data[['CARRIER_DELAY', 'WEATHER_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']]

# Split the data into training and testing sets
X_train, X_test, y_train_flight_duration,y_test_flight_duration, y_train_cancelled, y_test_cancelled, y_train_delay, y_test_delay = train_test_split(
    X,y_flight_duration, y_cancelled, y_delay_reasons, test_size=0.2, random_state=42
)

# Scale numerical features if necessary
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)          ## transfroming the test data with learning parameters of train data itself , so fit is not used inoder to avoid data leankage of test data


In [ ]:
X_train.shape

(47688, 20)

In [ ]:
X_train_scaled


array([[-1.23587182,  0.56937999, -0.59545213, ..., -1.28485413,
        -1.25945973,  0.        ],
       [ 0.37774647,  0.56937999, -0.59545213, ..., -1.00677119,
        -1.06349119,  0.        ],
       [ 0.14722957, -0.39848887, -0.4071615 , ..., -1.01941133,
        -1.08962033,  0.        ],
       ...,
       [-1.81216406,  1.53724886, -0.4071615 , ...,  0.25724214,
         0.24296574,  0.        ],
       [-0.77483802, -0.8824233 , -0.4071615 , ...,  0.30780267,
         0.32135315,  0.        ],
       [ 1.53033096, -1.36635773, -0.4071615 , ..., -0.04612106,
         0.11232004,  0.        ]])

In [ ]:
X_test_scaled

array([[ 0.83878026, -0.8824233 ,  1.09916351, ..., -0.33684413,
        -0.2926816 ,  0.        ],
       [ 1.64558941, -0.8824233 , -0.97203338, ...,  3.1265524 ,
         3.37846237,  0.        ],
       [ 0.14722957, -0.39848887, -0.59545213, ...,  0.73756721,
         0.64796738,  0.        ],
       ...,
       [-0.77483802, -0.8824233 , -0.4071615 , ...,  1.92573974,
         1.92829517,  0.        ],
       [ 0.26248802,  0.08544556, -0.4071615 , ...,  0.56060534,
         0.42586971,  0.        ],
       [ 1.64558941, -0.8824233 , -0.4071615 , ..., -1.14581266,
        -1.08962033,  0.        ]])

In [ ]:
y_delay_reasons

CARRIER_DELAY  WEATHER_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY
0                0.0            0.0             0.0                  0.0
1                0.0            0.0             0.0                  0.0
2                0.0            0.0             0.0                  0.0
3                0.0            0.0             0.0                  0.0
4                0.0            0.0             0.0                  0.0
...              ...            ...             ...                  ...
59605            0.0            0.0             0.0                 40.0
59606            0.0            0.0             0.0                  0.0
59607            0.0            0.0             0.0                  0.0
59608            0.0            0.0             0.0                  0.0
59609            0.0            0.0             0.0                 59.0

[59610 rows x 4 columns]

In [ ]:

# Define the ANN architecture
input_dim = X_train_scaled.shape[1]  ## gettunf column size
output_dim_flight_duration = 1
output_dim_cancelled = 1
output_dim_delay = y_train_delay.shape[1]

input_layer = Input(shape=(input_dim,))
hidden_layer = Dense(64, activation='relu')(input_layer)
# Add additional hidden layers if needed
output_layer_flight_duration = Dense(output_dim_flight_duration, activation= 'linear',name = 'flight_duration')(hidden_layer)
output_layer_cancelled = Dense(output_dim_cancelled, activation='sigmoid', name='cancelled')(hidden_layer)
output_layer_delay = Dense(output_dim_delay, activation='relu', name='delay_reasons')(hidden_layer)

model = Model(inputs=input_layer, outputs=[output_layer_flight_duration, output_layer_cancelled, output_layer_delay])

# Compile the model
model.compile(loss={'flight_duration':'mean_squared_error', 'cancelled': 'binary_crossentropy', 'delay_reasons': 'mean_squared_error'},
              optimizer='adam',
              metrics={'flight_duration':'mse','cancelled': 'accuracy', 'delay_reasons': 'mse'})




In [ ]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 20)]         0           []                               
                                                                                                  
 dense_1 (Dense)                (None, 64)           1344        ['input_2[0][0]']                
                                                                                                  
 flight_duration (Dense)        (None, 1)            65          ['dense_1[0][0]']                
                                                                                                  
 cancelled (Dense)              (None, 1)            65          ['dense_1[0][0]']                
                                                                                            

In [ ]:
## Early Stopping
import tensorflow as tf
early_stopping=tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5

)

In [ ]:
X_train_scaled.shape

(47688, 20)

In [ ]:
X_test_scaled.shape

(11922, 20)

In [ ]:
y_train_delay

CARRIER_DELAY  WEATHER_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY
8393             0.0            0.0             0.0                  0.0
36131            0.0            0.0             0.0                  0.0
32116            0.0            0.0             0.0                  0.0
37866           17.0            0.0             0.0                  0.0
10250            0.0            0.0             0.0                  0.0
...              ...            ...             ...                  ...
54343            0.0            0.0             0.0                  0.0
38158            0.0            0.0             0.0                  0.0
860              0.0            0.0             0.0                  0.0
15795            0.0            0.0             0.0                  0.0
56422            0.0            0.0             0.0                  0.0

[47688 rows x 4 columns]

In [ ]:
# Train the model
model.fit(X_train_scaled, {'flight_duration':y_train_flight_duration, 'cancelled': y_train_cancelled, 'delay_reasons': y_train_delay},  ## fitting each output layer with respective target data for training model
          epochs=30,
          batch_size=24,
          validation_data=(X_test_scaled, {'flight_duration':y_test_flight_duration,'cancelled': y_test_cancelled, 'delay_reasons': y_test_delay}))#, callbacks=early_stopping)


Epoch 1/30
1987/1987 [==============================] - 17s 7ms/step - loss: 8539.0283 - flight_duration_loss: 8029.3447 - cancelled_loss: 0.1184 - delay_reasons_loss: 509.5579 - flight_duration_mse: 8029.3447 - cancelled_accuracy: 0.9688 - delay_reasons_mse: 509.5579 - val_loss: 1124.1669 - val_flight_duration_loss: 726.0624 - val_cancelled_loss: 0.0776 - val_delay_reasons_loss: 398.0266 - val_flight_duration_mse: 726.0624 - val_cancelled_accuracy: 0.9849 - val_delay_reasons_mse: 398.0266
Epoch 2/30
1987/1987 [==============================] - 14s 7ms/step - loss: 881.7155 - flight_duration_loss: 467.9430 - cancelled_loss: 0.0721 - delay_reasons_loss: 413.7017 - flight_duration_mse: 467.9430 - cancelled_accuracy: 0.9855 - delay_reasons_mse: 413.7017 - val_loss: 591.1443 - val_flight_duration_loss: 240.6853 - val_cancelled_loss: 0.0712 - val_delay_reasons_loss: 350.3878 - val_flight_duration_mse: 240.6853 - val_cancelled_accuracy: 0.9849 - val_delay_reasons_mse: 350.3878
Epoch 3/30
198

In [ ]:
# Evaluate the model
losses = model.evaluate(X_test_scaled, {'flight_duration': y_test_flight_duration, 'cancelled': y_test_cancelled, 'delay_reasons': y_test_delay})

losses

373/373 [==============================] - 1s 3ms/step - loss: 323.7984 - flight_duration_loss: 42.0380 - cancelled_loss: 0.0505 - delay_reasons_loss: 281.7098 - flight_duration_mse: 42.0380 - cancelled_accuracy: 0.9882 - delay_reasons_mse: 281.7098


[323.7984313964844,
 42.03797149658203,
 0.05052853003144264,
 281.7098388671875,
 42.03797149658203,
 0.9881731271743774,
 281.7098388671875]

In [ ]:
from tensorflow.keras.models import Model, load_model

# Assuming you have trained and evaluated the model as mentioned in the previous code

# Save the model
model.save('flight_delay_model.h5')

# Load the model
loaded_model = load_model('flight_delay_model.h5')

In [ ]:
X_test.shape

(11922, 20)

In [ ]:
user_data = pd.DataFrame(X_test.loc[[44694]])
user_data_test = X_test
user_data_scaled_X_test = X_test_scaled

In [ ]:
type(user_data)

pandas.core.frame.DataFrame

In [ ]:

# Scale the new data using the same scaler used during training
#scaled_new_data = scaler.transform(user_data)
scaled_new_data = scaler.transform(user_data)



# Make predictions using the loaded model
prediction_flight_duration, predictions_cancelled, predictions_delay = loaded_model.predict(user_data_scaled_X_test)

## user single data
prediction_flight_duration_user, predictions_cancelled_user, predictions_delay_user = loaded_model.predict(scaled_new_data)


# Extract the predicted values
predicted_flight_duration = prediction_flight_duration.flatten()
predicted_cancelled = predictions_cancelled.flatten() >= 0.5  # Threshold for binary classification
predicted_delay = predictions_delay

# Extract the predicted values
predicted_flight_duration_user = prediction_flight_duration_user.flatten()
predicted_cancelled_user = predictions_cancelled_user.flatten() >= 0.5  # Threshold for binary classification
predicted_delay_user = predictions_delay_user

1/1 [==============================] - 0s 33ms/step


In [ ]:
predicted_flight_duration, predicted_cancelled, predicted_delay

(array([127.080124, 414.2811  , 203.27197 , ..., 294.2253  , 181.60349 ,
         66.44066 ], dtype=float32),
 array([False, False, False, ..., False, False, False]),
 array([[ 0.      ,  0.      ,  0.      ,  0.      ],
        [ 0.      ,  0.      ,  0.      ,  0.      ],
        [ 0.      ,  0.      ,  0.      ,  0.      ],
        ...,
        [ 0.      ,  0.      ,  0.      ,  0.      ],
        [ 0.      ,  0.      ,  0.      ,  0.      ],
        [41.021908,  0.      ,  0.      , 46.699333]], dtype=float32))

In [ ]:
predicted_delay.shape, type(predicted_delay), predicted_delay.ndim

((11922, 4), numpy.ndarray, 2)

In [ ]:
pd.DataFrame(predicted_delay)

0    1    2          3
0       0.000000  0.0  0.0   0.000000
1       0.000000  0.0  0.0   0.000000
2       0.000000  0.0  0.0   0.000000
3       0.000000  0.0  0.0   0.000000
4       0.000000  0.0  0.0   0.000000
...          ...  ...  ...        ...
11917   0.000000  0.0  0.0   0.000000
11918  13.315191  0.0  0.0   7.143476
11919   0.000000  0.0  0.0   0.000000
11920   0.000000  0.0  0.0   0.000000
11921  41.021908  0.0  0.0  46.699333

[11922 rows x 4 columns]

In [ ]:
prediction_flight_duration_user, predictions_cancelled_user, predictions_delay_user

(array([[127.080124]], dtype=float32),
 array([[0.01938589]], dtype=float32),
 array([[0., 0., 0., 0.]], dtype=float32))

In [ ]:
## checking the count of cancelled flights

count = 0
for x in predicted_cancelled:
  if x == True:
    count+= 1#count +1
print(count)

53


In [ ]:
## checking the count of cancelled flight of user

count = 0
for x in predicted_cancelled_user:
  if x == False:
    count+= 1#count +1
print(count)

1


In [ ]:
len(predicted_cancelled_user)

1

In [ ]:
pd.DataFrame(predictions_delay_user)

0    1    2    3
0  0.0  0.0  0.0  0.0

In [ ]:
df_duration = pd.DataFrame(predicted_flight_duration)
df_duration.max(), df_duration.min()

(0    721.600159
 dtype: float32,
 0    5.989613
 dtype: float32)

In [ ]:
data["ACTUAL_ELAPSED_TIME"].min()

38.0

In [ ]:
X_test

DAY_OF_MONTH  DAY_OF_WEEK  OP_UNIQUE_CARRIER  OP_CARRIER  \
44694            24            2                 12          12   
57879            31            2                  1           1   
31929            18            3                  3           3   
40236            22            7                  4           4   
34838            19            4                 13          13   
...             ...          ...                ...         ...   
32291            18            3                  4           4   
52912            28            6                 12          12   
15910            10            2                  4           4   
34212            19            4                  4           4   
58590            31            2                  4           4   

       OP_CARRIER_FL_NUM  ORIGIN_AIRPORT_ID  ORIGIN_CITY_MARKET_ID  \
44694               2271              13930                  30977   
57879                177              12478                  31703   
31929                 75              12478                  31703   
40236                752              15304                  33195   
34838                712              12953                  31703   
...                  ...                ...                    ...   
32291                870              12478                  31703   
52912               1199              11618                  31703   
15910                308              12892                  32575   
34212               1635              12953                  31703   
58590               2211              12953                  31703   

       ORIGIN_CITY_NAME  ORIGIN_STATE_ABR  DEST_AIRPORT_ID  \
44694                18                10            12953   
57879                62                25            14771   
31929                62                25            13495   
40236               101                 6            12953   
34838                62                25            10693   
...                 ...               ...              ...   
32291                62                25            12889   
52912                63                23            10792   
15910                51                 3            12478   
34212                62                25            13303   
58590                62                25            15096   

       DEST_CITY_MARKET_ID  DEST_CITY_NAME  DEP_TIME  DEP_DELAY  ARR_TIME  \
44694                31703              62     653.0       -7.0     957.0   
57879                32457              90    2100.0       -5.0      50.0   
31929                33495              61     831.0       -9.0    1054.0   
40236                31703              62    1609.0       -1.0    1827.0   
34838                30693              60    1320.0        0.0    1459.0   
...                    ...             ...       ...        ...       ...   
32291                32211              48     803.0       -2.0    1054.0   
52912                30792              11    2118.0       27.0    2248.0   
15910                31703              62     758.0       13.0    1549.0   
34212                32467              55    1104.0       -1.0    1405.0   
58590                35096             100    2335.0      100.0      38.0   

       ARR_DELAY  DIVERTED  CRS_ELAPSED_TIME  AIR_TIME  FLIGHTS  
44694      -18.0       0.0             135.0     102.0      1.0  
57879       -4.0       0.0             409.0     383.0      1.0  
31929      -26.0       0.0             220.0     174.0      1.0  
40236      -27.0       0.0             164.0     120.0      1.0  
34838       -1.0       0.0             160.0     130.0      1.0  
...          ...       ...               ...       ...      ...  
32291      -21.0       0.0             370.0     310.0      1.0  
52912       34.0       0.0              83.0      54.0      1.0  
15910      -10.0       0.0             314.0     272.0      1.0  
34212      -26.0       0.0     

In [ ]:
y_test_flight_duration

44694    124.0
57879    410.0
31929    203.0
40236    138.0
34838    159.0
         ...  
32291    351.0
52912     90.0
15910    291.0
34212    181.0
58590     63.0
Name: ACTUAL_ELAPSED_TIME, Length: 11922, dtype: float64

In [ ]:
data.iloc[44694]


DAY_OF_MONTH                24.0
DAY_OF_WEEK                  2.0
OP_UNIQUE_CARRIER           12.0
OP_CARRIER                  12.0
OP_CARRIER_FL_NUM         2271.0
ORIGIN_AIRPORT_ID        13930.0
ORIGIN_CITY_MARKET_ID    30977.0
ORIGIN_CITY_NAME            18.0
ORIGIN_STATE_ABR            10.0
DEST_AIRPORT_ID          12953.0
DEST_CITY_MARKET_ID      31703.0
DEST_CITY_NAME              62.0
DEP_TIME                   653.0
DEP_DELAY                   -7.0
ARR_TIME                   957.0
ARR_DELAY                  -18.0
CANCELLED                    0.0
DIVERTED                     0.0
CRS_ELAPSED_TIME           135.0
ACTUAL_ELAPSED_TIME        124.0
AIR_TIME                   102.0
FLIGHTS                      1.0
CARRIER_DELAY                0.0
WEATHER_DELAY                0.0
SECURITY_DELAY               0.0
LATE_AIRCRAFT_DELAY          0.0
Name: 44694, dtype: float64

In [ ]:
data['CANCELLED'].unique()

array([0., 1.])