<a href="https://colab.research.google.com/github/krishnan5307/-5307-krishnan/blob/main/Sentiment_analysis_lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
df =pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Sentiment_analysis_LSTM/twitter.csv')

In [ ]:
df.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [ ]:
len(df.columns)

3

In [ ]:
df['label'].unique()

array([0, 1])

In [ ]:
df.shape

(31962, 3)

In [ ]:
data= df[0:10000]

In [ ]:
labels = data['label']
type(labels)


pandas.core.series.Series

In [ ]:
# Remove '@user' from every row in the 'Sentences' column
data['tweet'] = data['tweet'].str.replace('@user', '').str.strip()

<ipython-input-12-6c42c54c67f8>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tweet'] = data['tweet'].str.replace('@user', '').str.strip()


In [ ]:
data.head()

id  label                                              tweet
0   1      0  when a father is dysfunctional and is so selfi...
1   2      0  thanks for #lyft credit i can't use cause they...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [ ]:
import re
# Remove special characters from the 'Sentences' column
data['tweet'] = data['tweet'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))   #matches any character that is not an alphanumeric character (a-zA-Z0-9) or whitespace (\s), and the ^ inside the square brackets negates the character class.


<ipython-input-14-3b6c9f66a720>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tweet'] = data['tweet'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))   #matches any character that is not an alphanumeric character (a-zA-Z0-9) or whitespace (\s), and the ^ inside the square brackets negates the character class.


In [ ]:
data.head()

id  label                                              tweet
0   1      0  when a father is dysfunctional and is so selfi...
1   2      0  thanks for lyft credit i cant use cause they d...
2   3      0                                bihday your majesty
3   4      0  model   i love u take with u all the time in ur 

4   5      0               factsguide society now    motivation

In [ ]:
data['tweet'] = data['tweet'].str.lower()

<ipython-input-16-d214e596c08d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tweet'] = data['tweet'].str.lower()


In [ ]:
# Set 'id' column as the index
data.set_index('id', inplace=True)

In [ ]:
data.tail()

label                                              tweet
id                                                             
9996       0  my routine is out of whack evening walk  walk ...
9997       0  im dead but still happy poledance madrid fitne...
9998       0   united kingdom claimant count rate up to 22 i...
9999       0  rip my friend  shocked   dismay heabroken cann...
10000      0  how to open your   loving hea  thursdaythought...

In [ ]:
data.dtypes

label     int64
tweet    object
dtype: object

In [ ]:
# list = data['tweet'].to_list()
# list

# integer encoding

In [ ]:
# from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,Embedding,Flatten, LSTM

In [ ]:
tokenizer = Tokenizer(oov_token='<nothing>')

In [ ]:
## taking only ist 10K documents

final_data = data['tweet']

In [ ]:
tokenizer.fit_on_texts(final_data) # DOING TOKEINZATION

In [ ]:
## VOCABULARY

tokenizer.word_index     ## here at first we can see the oov is also tokenzied

{'<nothing>': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'i': 5,
 'you': 6,
 'and': 7,
 'in': 8,
 'for': 9,
 'of': 10,
 'is': 11,
 'my': 12,
 'love': 13,
 'on': 14,
 'it': 15,
 'with': 16,
 'this': 17,
 'be': 18,
 'day': 19,
 'all': 20,
 'so': 21,
 'are': 22,
 'that': 23,
 'happy': 24,
 'me': 25,
 'your': 26,
 'have': 27,
 'amp': 28,
 'at': 29,
 'its': 30,
 'just': 31,
 'we': 32,
 'not': 33,
 'u': 34,
 'when': 35,
 'will': 36,
 'do': 37,
 'am': 38,
 'im': 39,
 'today': 40,
 'life': 41,
 'time': 42,
 'from': 43,
 'what': 44,
 'but': 45,
 'out': 46,
 'new': 47,
 'up': 48,
 'now': 49,
 'positive': 50,
 'about': 51,
 'like': 52,
 'people': 53,
 'thankful': 54,
 'was': 55,
 'our': 56,
 'as': 57,
 'get': 58,
 'bihday': 59,
 'by': 60,
 'good': 61,
 'see': 62,
 'cant': 63,
 'one': 64,
 'how': 65,
 'dont': 66,
 'smile': 67,
 'more': 68,
 'no': 69,
 'can': 70,
 'go': 71,
 'they': 72,
 'if': 73,
 'fathers': 74,
 'who': 75,
 'take': 76,
 'weekend': 77,
 'work': 78,
 'want': 79,
 'fun': 80,
 'healthy': 81,


In [ ]:
len(tokenizer.word_index.keys())

19604

In [ ]:
list_tokens = list(tokenizer.word_index.values())
max(list_tokens), min(list_tokens)

(19604, 1)

In [ ]:
tokenizer.word_counts

OrderedDict([('when', 405),
             ('a', 1966),
             ('father', 54),
             ('is', 1345),
             ('dysfunctional', 1),
             ('and', 1514),
             ('so', 596),
             ('selfish', 4),
             ('he', 154),
             ('drags', 1),
             ('his', 172),
             ('kids', 55),
             ('into', 62),
             ('dysfunction', 1),
             ('run', 27),
             ('thanks', 83),
             ('for', 1440),
             ('lyft', 4),
             ('credit', 4),
             ('i', 1800),
             ('cant', 257),
             ('use', 39),
             ('cause', 20),
             ('they', 217),
             ('dont', 253),
             ('offer', 13),
             ('wheelchair', 2),
             ('vans', 1),
             ('in', 1448),
             ('pdx', 1),
             ('disapointed', 1),
             ('getthanked', 1),
             ('bihday', 273),
             ('your', 541),
             ('majesty', 5),
             (

In [ ]:
tokenizer.document_count

10000

In [ ]:
# Get the unique words (vocabulary)
len(tokenizer.word_index)

19604

In [ ]:
sequences = tokenizer.texts_to_sequences(final_data)
sequences

[[35,
  4,
  289,
  11,
  6879,
  7,
  11,
  21,
  2679,
  101,
  6880,
  84,
  287,
  256,
  84,
  6881,
  549],
 [199,
  9,
  2680,
  2681,
  5,
  63,
  396,
  731,
  72,
  66,
  1056,
  4328,
  6882,
  8,
  6883,
  6884,
  6885],
 [59, 26, 2260],
 [122, 5, 13, 34, 76, 16, 34, 20, 2, 42, 8, 110, 126],
 [2682, 1303, 49, 280],
 [2683,
  766,
  578,
  4329,
  7,
  264,
  487,
  254,
  72,
  320,
  2684,
  7,
  193,
  6886,
  35,
  72,
  58,
  98,
  6887],
 [2261, 117, 6888],
 [2,
  156,
  281,
  170,
  11,
  2,
  170,
  9,
  1731,
  63,
  128,
  51,
  23,
  281,
  1731,
  215,
  1553,
  2262,
  6889,
  140],
 [32, 982, 13, 2, 1426, 6890, 1304, 4330, 983, 6891],
 [631, 106, 39, 30, 21, 1946],
 [884,
  2685,
  1140,
  1305,
  348,
  6892,
  43,
  984,
  2263,
  3,
  3285,
  8,
  214,
  118,
  155,
  146,
  171],
 [32, 22, 21, 2679, 130, 6893, 1732, 669, 6894, 2679, 1306, 2686, 13],
 [5, 58, 3, 62, 12, 475, 40, 6895, 6896],
 [2687, 1307, 6897, 1427, 281, 1733, 2, 1947, 6898, 1948],
 [69, 1

# padding

In [ ]:
data_padded = pad_sequences(sequences,padding='post',maxlen=20)
data_padded[0:3]

array([[  35,    4,  289,   11, 6879,    7,   11,   21, 2679,  101, 6880,
          84,  287,  256,   84, 6881,  549,    0,    0,    0],
       [ 199,    9, 2680, 2681,    5,   63,  396,  731,   72,   66, 1056,
        4328, 6882,    8, 6883, 6884, 6885,    0,    0,    0],
       [  59,   26, 2260,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [ ]:
type(data_padded), data_padded.ndim, data_padded.shape

(numpy.ndarray, 2, (10000, 20))

# DOing keras embedding just for demonstration but we will only pass the padded data in model as we are adding tbe keras embedding layer in the model , so no need to do seperate as it will create dimensionality issue

In [ ]:
model = Sequential()
model.add(Embedding(len(tokenizer.word_index),output_dim=2,input_length=20))  ## 23 = unique words in vocabulary len(tokenizer.word_index) =23 , out_dim =2 means higher dimension output the model generates after learning ,
                                                              ## input_length=5 means length of padding or sentences passing

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, 20, 2)             39208     
                                                                 
Total params: 39,208
Trainable params: 39,208
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(data_padded)  ## 2D vector ggeenerated afyer leaning, this is not constant bcpoz its weights  will get updated internally with RNN, LSTM or GRU during back propogation in training
print(pred)


313/313 [==============================] - 0s 1ms/step
[[[-0.00610616 -0.04682887]
  [-0.03491157 -0.01016328]
  [-0.00055442  0.04588679]
  ...
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]]

 [[-0.0206869   0.04150854]
  [ 0.0464008  -0.02830074]
  [-0.00838945  0.04645014]
  ...
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]]

 [[-0.03822237  0.0162838 ]
  [-0.0499009   0.03164449]
  [-0.04143386 -0.02687719]
  ...
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]]

 ...

 [[ 0.04547353 -0.04061731]
  [-0.02423086 -0.01134811]
  [ 0.0190238  -0.0315293 ]
  ...
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]]

 [[ 0.03269193 -0.01793446]
  [ 0.01462345  0.02140286]
  [-0.03048939  0.02423579]
  ...
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]
  [-0.02960539 -0.01840291]]

 [[-0.0379864   0.03745228]
  [ 0.02482272 -0.01853112]
  [

In [ ]:
len(pred)

10000

# Sentiment analysis

In [ ]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_labels, test_labels = train_test_split(data_padded,labels, test_size=0.2, random_state=42)

In [ ]:
len(train_data), len(test_data), len(train_labels), len(test_labels)

(8000, 2000, 8000, 2000)

In [ ]:
type(train_data), type(train_labels)

(numpy.ndarray, pandas.core.series.Series)

In [ ]:
train_data.shape

(8000, 20)

In [ ]:
train_data

array([[1094,   12,  242, ...,    0,    0,    0],
       [  11,  480, 1440, ...,    0,    0,    0],
       [ 125,  828,   12, ...,    0,    0,    0],
       ...,
       [ 157,    9,    4, ..., 2345, 2115,  773],
       [ 217, 4722,  163, ...,    0,    0,    0],
       [ 636,  636,  953, ...,    0,    0,    0]], dtype=int32)

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) ,output_dim= 2,input_length=20))  ## this is not constant bcpoz its weights  will get updated internally with RNN, LSTM or GRU during back propogation in training
model.add(LSTM(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 2)             39208     
                                                                 
 lstm (LSTM)                 (None, 32)                4480      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 43,721
Trainable params: 43,721
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(train_data, train_labels,epochs=5,validation_data=(test_data,test_labels))

Epoch 1/5
250/250 [==============================] - 25s 68ms/step - loss: 0.2848 - acc: 0.9289 - val_loss: 0.2383 - val_acc: 0.9245
Epoch 2/5
250/250 [==============================] - 4s 17ms/step - loss: 0.1333 - acc: 0.9536 - val_loss: 0.1730 - val_acc: 0.9425
Epoch 3/5
250/250 [==============================] - 2s 9ms/step - loss: 0.0652 - acc: 0.9803 - val_loss: 0.1906 - val_acc: 0.9285
Epoch 4/5
250/250 [==============================] - 3s 13ms/step - loss: 0.0340 - acc: 0.9911 - val_loss: 0.1947 - val_acc: 0.9410
Epoch 5/5
250/250 [==============================] - 4s 17ms/step - loss: 0.0190 - acc: 0.9954 - val_loss: 0.2501 - val_acc: 0.9420


In [ ]:
pred_array = model.predict(test_data)
pred_array

63/63 [==============================] - 0s 2ms/step


array([[0.00020787],
       [0.00024571],
       [0.0134259 ],
       ...,
       [0.00085417],
       [0.00019952],
       [0.00018826]], dtype=float32)

In [ ]:
transformed_values = list(map(lambda val: 1 if val >= 0.5 else 0, pred_array))

# Count the occurrences of 0s and 1s
from collections import Counter

counted_values = Counter(transformed_values)

# Print the counts
print("negative sentiment for the tweet:", counted_values[0])
print("positive sentiment for the tweet:", counted_values[1])

negative sentiment for the tweet: 1877
positive sentiment for the tweet: 123
